### ISSUE TITLE
strata-market :Bound mismatch: The method of(Integer, ?) of type Pair is not applicable for the arguments (int, ?). The wildcard parameter ? has no lower bound, and may actually be more restrictive than argument ?

### ISSUE THREAD

**Issue by dapperturban** [OpenGamma/Strata#1073]
Installed Strata and using within eclipse luna.
I am having this error:
Bound mismatch: The method of(Integer, ?) of type Pair is not applicable for the arguments (int, ?). The wildcard parameter ? has no lower bound, and may actually be more restrictive than argument ?

This is where the error is coming:

```
  public CurvePointShiftsBuilder addShifts(int scenarioIndex, Map<?, Double> shiftMap) {
    ArgChecker.notNull(shiftMap, "shiftMap");
    ArgChecker.notNegative(scenarioIndex, "scenarioIndex");
    MapStream.of(shiftMap).forEach((id, shift) -> shifts.put(Pair.of(scenarioIndex, id), shift));
    return this;
  }

```

**Comment by jodastephen** [comment]
We recommend using Java 8 update 40 or later and Eclipse Mars update 1 (4.5.1) or later (the latest Eclipse release is 4.5.2). Issues with Eclipse Luna are expected as Mars is the first proper release with Java 8 support.

**Comment by cjkent** [comment]
Where are you getting the error? I'm seeing that marked as an error in IntelliJ but it compiles fine using JDK 8u60. So there's clearly a bug in IntelliJ's type inference.
