### ISSUE TITLE
strata-measure: The method getValue(MarketDataId<T>) in the type ScenarioMarketData is not applicable for the arguments (? extends MarketDataId<?>)

### ISSUE THREAD

**Issue by dapperturban** [OpenGamma/Strata#1074]
I am getting this error:
The method getValue(MarketDataId<T>) in the type ScenarioMarketData is not applicable for the arguments (? extends MarketDataId<?>)

on this code:
```
  private static Map<? extends MarketDataId<?>, MarketDataBox<?>> getMarketDataValues(
      ScenarioMarketData marketData,
      Set<? extends MarketDataId<?>> ids,
      ObservableSource observableSource) {

    return ids.stream().collect(toImmutableMap(k -> k, k -> marketData.getValue(k)));
  }
```

This is in the :CurveInputsMarketDataFunction.java:

**Comment by cjkent** [comment]
This also causes problems in the latest version of IntelliJ but it compiles fine under JDK 8u60.

https://youtrack.jetbrains.com/issue/IDEA-157586
