### ISSUE TITLE
Pricing individual financial instruments

### ISSUE THREAD

**Issue by dapperturban** [OpenGamma/Strata#1101]
I have managed to successfully install Strata using Eclipse and I have run all the example codes, but how do I price an individual financial instrument.

For example, if I don't want to use the Calculation Runner and I want to just provide my own data and price an option or a swap or a bond. Essentially, I want to use the Pricer module to price my own data.

How do I accomplish that?

**Comment by jodastephen** [comment]
This kind of question would probably be better asked on our [forums](http://forums.opengamma.com/).

The answer is that you can use Strata at three different levels

* calculation - using `CalculationRunner`
* measure - using classes such as `SwapTradeCalculations` (added very recently)
* pricing - using classes such as `DiscountingSwapTradePricer`

In your case, we would recommend using the new measure-level API. Using the API is simple:

    SwapTrade trade = ...   // create trade
    RatesProvider ratesProvider = ...   // create market data
    ResolvedSwapTrade resolved = trade.resolve(ReferenceData.standard());
    MultiCurrencyAmount pv = SwapTradeCalculations.DEFAULT.presentValue(resolved, ratesProvider);

(Usage of the pricer-level API is very similar, but we feel the measure-level API is better suited for applications.)

As well as pricing a single trade against a single set of market data, the measure-level API provides the ability to price a single trade against a set of scenarios. If you need to price more than one trade in a mixed portfolio, we recommend using `CalculationRunner`.

**Comment by dapperturban** [comment]
I am sorry, I still don't understand how to create the trade.
I have taken your example, I made a public static main method and placed the code you have told me to. But how do I create the Trade and how do I reference the market data?

```
  public static void main(String[] args) {
	SwapTrade trade = ... ;// create trade
	RatesProvider ratesProvider = ...;//create market data
	ResolvedSwapTrade resolved = trade.resolve(ReferenceData.standard());
	MultiCurrencyAmount pv = SwapTradeCalculations.DEFAULT.presentValue(resolved, ratesProvider);
	
	  
  }
```

**Comment by jodastephen** [comment]
The example code shows how to create trades. see `SwapPricingExample` and `SwapTradeModelDemo`. Alternatively, you can use the strata-loader project to load a trade from FpML, see `FpmlDocumentParser`.

The `RatesProvider` can be created manually or by calibrating a set of curves. To create it manually, see `ImmutableRatesProvider`, which has a builder that allows discount curves, forward curves and FX rates to be added. `SwapEnd2EndTest` contains a method that creates a rates provider which would be good to look at.

Let us know how you get on, or if you need to calibrate curves.

**Comment by dapperturban** [comment]
Thank you for you help, i worked through the examples and I understand how to use the Calculation module. I feel that is currently the most useful for my needs.
I wanted to ask how I could pass a portfolio through it. Looking at the "SwapPricingExample", instead of  creating all the trades individually, how do I pass/input the "swap-portfolio.xml" instead?

Thank you

**Comment by jodastephen** [comment]
We recommend using FpML as the trade input format. swap-portfolio.xml is in our internal Joda-Bean xml format which is not guaranteed to be stable over time. If you do want to parse 

To parse FpML, use `FpmlDocumentParser`, which returns a `List<Trade>` ready for input to `CalculationRunner`.

If you do want to use the Joda-Bean format, `TradeListParameterConverter` and its superclass `JodaBeanParameterConverter` contain the essential code to load the data.

**Comment by dapperturban** [comment]
Is there an example of how to use the FpmlDocumentParser and is there an example FpML file?

**Comment by jodastephen** [comment]
The only code using FpML is the test case `FpmlDocumentParserTest`. It is not particularly hard to use - your main problem is likely to be learning FpML. The test case makes use of some example FpML documents, such as `ird-ex01-vanilla-swap.xml` (and others in the same directory).

**Comment by dapperturban** [comment]
I am sorry, I am a bit lost....
I have gone through the FpmlDocumentParserTest and think I understand how the structure is set out to pull the FpML file:
```
	String location = "classpath:com/opengamma/strata/loader/fpml/ird-ex01-vanilla-swap.xml";
	ByteSource resource = ResourceLocator.of(location).getByteSource();
	List<Trade> trades = FpmlDocumentParser.of(FpmlPartySelector.matching("Party1")).parseTrades(resource);
```
what I am unable to do is, use this code in the "SwapPricingExample". I want to run the SwapPricingExample using a FpML document, so I do not need to create all the trades manually as is done in the "SwapPricingExample".

**Comment by jodastephen** [comment]
Within the `SwapPricingExample` that we supply, simply replace the current `createSwapTrades()` method with one that loads from FpML based on the code above. The `createSwapTrades()` method returns `List<Trade>`, which matches what you get from FpML.

Once that is achieved, you will then need to ensure that the market data is available for the swaps in the FpML file.

**Comment by jodastephen** [comment]
Looking closer, you may be struggling because the file "ird-ex01-vanilla-swap.xml" is not on the classpath (it is in the *test* area of a different module, thus it will not be on the classpath when you run the example).

It may be easier to start with a `File`, as you can use `File.exists()` to check that the file is found. This code works on my box, but you'll have to adjust the absolute path:

    File dir = new File("/dev/opengamma/strata/modules/loader/src/test/resources/com/opengamma/strata/loader/fpml/");
    ByteSource resource = ResourceLocator.ofFile(new File(dir, "ird-ex01-vanilla-swap.xml")).getByteSource();

**Comment by dapperturban** [comment]
It worked great, thank you. I also tried the same code I wrote earlier but instead I changed "classpath:" with "file:" and that worked as well.

If I have more questions, I will post them on the Forums from now on.
Thank you
