### ISSUE TITLE
Consider renaming CurveGroupConfiguration to CurveMappings

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1163]
`CurveGroup` is much less relevant than it used to be, but `CurveGroupConfiguration` is a key part of the market data setup. It might be better to rename it `CurveMappings`. It describes what it does much more clearly and it breaks the link with the name of the largely irrelevant `CurveGroup`.

**Comment by jodastephen** [comment]
`CurveGroupConfiguration` now contains more than just curve mappings.
