### ISSUE TITLE
Need FloatingRateName for USD-FEDFUND

### ISSUE THREAD

**Issue by jacbop** [OpenGamma/Strata#1227]
Existing CCP data references this index as USD-FEDFUND (no dash).

The following names are currently supported
```
USD-FED-FUND = USD-FED-FUND
USD-Federal Funds-H.15-OIS-COMPOUND = USD-FED-FUND
USD-FEDFUND-H.15-OIS-COMPOUND = USD-FED-FUND
```

**Comment by cjkent** [comment]
`FloatingRateName` only includes FpML names. If `USD-FEDFUND` is an FpML name for that index then it makes sense to add it.

If not, you can add names to `FloatingRateName` without adding them to Strata. Create a file on the classpath called `/com/opengamma/strata/config/application/FloatingRateNameData.ini` containing the mappings and it will be loaded by Strata.

Check the Javadoc of `ResourceConfig` for details.

**Comment by jodastephen** [comment]
If the code is an end user application use `/com/opengamma/strata/config/application/FloatingRateNameData.ini`. If it is a library produced by OpenGamma, use `/com/opengamma/strata/config/library/FloatingRateNameData.ini`

**Comment by jacbop** [comment]
Thank you. This is for an OG Library. One of the supported CCPs provides reset and curve data under the name USD-FEDFUND. I try out changes to the ini file and close the ticket once I have it working.
