### ISSUE TITLE
Add methods to CsvRow to handle empty fields

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1228]
The `getField` and `findField` methods on `CsvRow` return an empty string if there is no value for a field. This is such a common case that it would be helpful if there were methods which treated an empty value as missing:

```
String getValue(String fieldName);
Optional<String> findValue(String fieldName);
```

**Comment by jodastephen** [comment]
The current code returns empty string if the column is found but there is no data. That seems reasonable to me, and better than optional empty or an exception.

**Comment by cjkent** [comment]
I'm suggesting this as a useful addition to the existing behaviour, not a replacement for it.

A lot of the files I'm parsing with `CsvFile` have many columns with optional values. So I have to check for empty strings everywhere. An empty string is fundamentally different to any other value in most cases as it can't be parsed into anything interesting. That's why it would be useful to be able to treat it as a missing value.
