### ISSUE TITLE
Add factory methods to FxRateProvider

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1231]
Creating multi-scenario FX rates is done like this:

    ScenarioFxRateProvider.of(scenarioMarketData);

Single-scenario rates are done like this:

    MarketDataFxRateProvider.of(marketData);

It would be more consistent and more discoverable if these methods existed:

    FxRateProvider.of(MarketData);
    FxRateProvider.of(MarketData, ObservableSource);

**Comment by jodastephen** [comment]
`FxRateProvider` is in strata-basics, so does not have access to `MarketData`.
