### ISSUE TITLE
Public factory methods for Failure

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1302]
I would like to create a `Failure` from multiple `Result` instances. At the moment I'm doing this which smells a bit bad:

    Failure failure = Result.failure(result1, result2, result3, ...).getFailure();

It would be cleaner if I didn't have to create and discard a `Result` just to get at its failure.

**Comment by jodastephen** [comment]
I don't think a `Failure.of(result1, result2, ...)` API would be good. Nor would `Failure.of(result1.getFailure(), result2.getFailure(), ...)`.

**Comment by cjkent** [comment]
The first of those would be better for my use case than what I'm doing currently.

The second wouldn't work. `Result.failure()` accepts a mixture of successful and failed results and creates a result which only contains the failures. Calling `getFailure()` on a successful result will throw an exception.

**Comment by cjkent** [comment]
It's not a big problem, I'll carry on creating an intermediate result.
