### ISSUE TITLE
Currency doesn't work with non-standard serialization

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1321]
`Currency` computes a hash code in the constructor which is unique across all possible currency codes. This is used as the basic of the `equals` method. The hash code field is `transient`. The `readResolve` method looks up the deserialized currency in a cache and creates a new instance if a cached instance is not available.

If a currency instance is deserialized using a non-standard serialization framework the code will be populated but `readResolve` will not be called. This means the cache and the constructor will be bypassed and none of the transient fields will be populated. The hash code will be zero. 

This means that a deserialized currency instance will not be equal to a normal currency instance with the same 3-letter code. It also means that all deserialized instances will be equal to each other regardless of the code.

**Comment by jodastephen** [comment]
The `transient` modifier is a standard part of Java and is handled by `readResolve()`. External serialization systems should respect that, and if it cannot handle it then it is broken. For Kryo, this means writing a dedicated serializer.

**Comment by cjkent** [comment]
That's true, but it is actually necessary to use `readResolve` or could we use a different approach that is more resilient?

**Comment by jodastephen** [comment]
Both `transient` and `readResolve()` are essential parts of Java that we need to be able to use.
