### ISSUE TITLE
Review all implementations of readResolve

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1322]
We have had two issues recently because `readResolve` is not necessarily called when using a non-standard serialization framework (#1321 #1319).

Any class which relies on `readResolve` for correctness is likely to fail when used with a custom serialization framework which doesn't have the same semantics as default serialization.

We should review all `readResolve` implementations and ensure the behaviour is still correct if it is not called after deserialization.

**Comment by jodastephen** [comment]
I took a hard line on this with Joda-Time and we should too. `readResolve()` is a standard widely used concept, and our code, and the libraries we use, need to be able to use it. It looks like the Kryo framework can support it, with additional configuration.

**Comment by cjkent** [comment]
I have no problem with using `readResolve` to enforce invariants. If a user chooses to use a custom serialization framework and also edits the serialized data to break an invariant there's nothing we can do and I don't think anyone would expect anything else.

I think relying on `readResolve` for correctness is unnecessarily hostile. Strata is a library and therefore not necessarily the most important part of the system and not in a position to dictate the serialization strategy. 

What is the benefit of taking a hard line and having classes which behave incorrectly without `readResolve`? Looking at the code, I can see three different uses of `readResolve`

1. Checking invariants
1. Recalculating transient fields
1. Returning a cached object instead of the deserialized instance

The first use case isn't really a problem as I mentioned above.

All the transient fields I've seen were simple values that could easily be part of the serialized form, for example `Currency` (#1321). Why not serialize them? Is it just to save space? Is it worth making the class more fragile for that?

The third case needn't be an issue, as long as we don't rely on object identity in any of our equality checking.

**Comment by jodastephen** [comment]
Kryo and Joda-Beans don't actually get on at all. Kryo doesn't like immutable beans without no-args constructors. See [this Joda-Beans change](https://github.com/JodaOrg/joda-beans/commit/bd707a95772688853dcdd53a78825e484dd2d6e1) for a better solution.

**Comment by cjkent** [comment]
That solves the immediate problem, but at the cost of some complexity. A person using Strata and Kryo now has to know about Joda Beans too. Specifically, they need to:

* Figure out that Strata uses Joda Beans for serialization
* Find out that Joda Beans has support for Kryo
* Integrate Joda Beans and Kryo

That raises the barrier to entry, which is something we've worked hard to lower. If Strata didn't rely on `readResolve` for correctness none of that would be necessary. Kryo (and any similar framework) would just work. 

I'm still not sure what problem we're trying to solve. Take `Currency` as an example. The transient fields are 2 `int` and 1 `String` which could easily be serialized. Why make them transient?

`HolidayCalendarId` had a similar problem because it relied on a static cache of values and used reference equality for performance. Switching to a normal `equals` implementation actually improved performance by a tiny amount and made the behaviour more standard and robust.

Are there any cases in the codebase where using `readResolve` is the only possible way to ensure correctness? If not then why not use a different approach which sidesteps these problems?

**Comment by jodastephen** [comment]
The goal is to support Kryo, and `readResolve`/`transient` is a red herring for that. The only way to support immutable beans in Kryo that I could see was to fully take control using a serializer. If someone has invested time in using Kryo and Strata, they will find the solution to link the two.

As a general rule, I would never change a `transient` field to be non-transient for something like this. Serialized state should not duplicate information, and validating input is important to guard against malicious input.  In any case, `HolidayCalendarId` has a transient lambda, so it won't work (and although it is weirdly faster, the previous fix didn't actually make the class work with Kryo).

**Comment by cjkent** [comment]
That's puzzling. The reported issues were that instances of `Currency` and `HolidayCalendarId` which had been deserialized with Kryo were not equal to the original instances. There were no reports of problems serializing and deserializing them.

**Comment by jodastephen** [comment]
Both `transient` and `readResolve()` are essential parts of Java that we need to be able to use.
