### ISSUE TITLE
CalculationFunction should only be asked for measures it declares it supports

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1336]
The method `CalculationFunction.supportedMeasures` returns the set of measures the function is able to calculate. If the user requests unsupported measures they are passed to the `requirements` and `execute` method and the function must handle them and return a failure `Result` containing `UNSUPPORTED`.

It would simplify every function if the set of measures passed into the function only included measures that the function claims to support. The `Result` instances for unsupported measures could be created by `CalculationTask`.

**Comment by jodastephen** [comment]
The implementation fails to match the existing Javadoc.
