### ISSUE TITLE
Provide rounding to CurrencyAmount

### ISSUE THREAD

**Issue by andreiruse** [OpenGamma/Strata#1355]
We have a requirement that the amounts represented by the Strata `CurrencyAmount` object should have as many decimals as the currency specification. The full list is specified by [ISO 4217](http://www.currency-iso.org/en/home/tables/table-a1.html).

Having a `rounded()` method on CurrencyAmount that exposes the already-rounded amount would help for this use case.

**Comment by cjkent** [comment]
Would this be best implemented as a factory method `CurrencyAmount.ofRounded()`?
