### ISSUE TITLE
ExplainKey.FROM_FIXING_SERIES is only populated if the fixing date equals the valuation date

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1380]
This seems surprising. It would seem reasonable to populate it if the fixing date is on or before the valuation date and the fixing series contains the fixing date. The Javadoc says 

>"The flag to indicate that the that the observed value is from a fixing time-series."

The valuation date isn't mentioned anywhere and the user of this field needs to know how it's populated.

**Comment by jodastephen** [comment]
The implementation in `IborIndexRates` is wrong
