### ISSUE TITLE
ZC

### ISSUE THREAD

**Issue by karin100** [OpenGamma/Strata#1392]
Hi,
We have a ZC trade and got different results then expected.
This is what we got using the fpml parser : PV01CalibratedSum :-101759.454362
And this is what expected (using bloomberg terminal) : 192308.86
Any idea what went wrong here?

[xxxx001 IRD inflation ESP-CPI executionNotification from Sef - Blomm-10.txt](https://github.com/OpenGamma/Strata/files/538859/xxxx001.IRD.inflation.ESP-CPI.executionNotification.from.Sef.-.Blomm-10.txt)
![bloomberg](https://cloud.githubusercontent.com/assets/22726109/19518004/41538564-960d-11e6-88be-12043f620b70.jpg)

**Comment by jodastephen** [comment]
Thanks for asking, but our primary channel for user questions is our [forum](http://strata.opengamma.io/support/).
