### ISSUE TITLE
Simple startegy implementation

### ISSUE THREAD

**Issue by Almaz-KG** [OpenGamma/Strata#1460]
Hello guys!

Can you help me to find some sample implementation of simple strategy?
I wanna to do something like:
1. Download Historical EOD data stocks
2. Implement my own simple strategy based on RSI, Stochastic and etc
3. Run my strategy Impl on historical data (see 1.)
4. Build result report
5. Save and show report

Some times ago I start implement simple library and quit it because project was difficult for me. On Strata I want to do like this sample [Germes/Sample](https://github.com/Almaz-KG/Germes#examples)

If you have some questions or etc - please ask me

P.S. I really apologize for my bad English, but I try to improve it)

**Comment by jodastephen** [comment]
Sorry that I didn't see this earlier - our primary place for questions like this is our [forum](http://forums.opengamma.com/). Please can you ask your question there.
