### ISSUE TITLE
Allow ValueWithFailures to be easily combined

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1493]
I've come across a few cases where I've had to retrofit `ValueWithFailures` to code that uses streams. In order to collect the values and failures from multiple calculations it was necessary to convert the streams code into a for loop and accumulate into mutable containers. This is unfortunate and could be avoided if there were an easy way to combine multiple `ValueWithFailures` instances. The obvious options are:

1. Add `ValueWithFailures.combinedWith(ValueWithFailures<T>, BinaryOperator<T>)`. This could be used with `Stream.reduce()`
2. Add `Guavate.toValueWithFailures(T, BinaryOperator<T>)` returning a `Collector`
3. Add `ValueWithFailures.of(T, BinaryOperator<T>, ValueWithFailures<T>...)` and `ValueWithFailures(T, BinaryOperator<T>, List<ValueWithFailures<T>>)`

I think option 1) might be awkward because it would require nested lambdas inside the call to `reduce`. Option 2) would fit the streams use case pretty naturally and seems like a good option. Option 3) is probably worth doing too because it's simple and uncontroversial.

**Comment by cjkent** [comment]
Option 1) was addressed by 7e152f08cb27329cf3d7101a774be4380a774ac6.

Leaving the issue open as 2) and 3) would still be useful.

**Comment by jodastephen** [comment]
Item 2 has been added.
