### ISSUE TITLE
Overload methods on EtdIdUtils to take EtdContractSpec and security instances

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#1497]
`EtdIdUtils` has helper methods to create IDs for `EtdContractSpec`, `EtdOptionSecurity` and `EtdFutureSecurity`. These methods have separate parameters for each item of information, for example the exchange ID and contract code.

There are cases where you need to generate an ID from an existing contract spec or security and it would be useful if there were overloads for this.

**Comment by jodastephen** [comment]
`EtdFutureSecurity.of()` already exists to do this? Or am I missing something.

**Comment by cjkent** [comment]
No, it was me that was missing something :)
