### ISSUE TITLE
API for "MarketOpeningsCalendar"

### ISSUE THREAD

**Issue by nimo23** [OpenGamma/Strata#1519]
Please provide a API for something like "MarketOpeningsCalendar".

"MarketOpeningsCalendar" can inherit/extend from "HolidayCalendar" but with support of the opening times ("trading hours") of a stock market. For example, something like this:

```
StockMarketOpeningCalendarId id = StockMarketOpeningCalendarId.NYSE;
StockMarketOpeningCalendar  cal = id.resolve(ReferenceData.standard());
// returns true, if stock market is actually open
cal.isOpen(myLocalDateTime)
// returns the next open localDateTime
LocalDateTime myNewLocalDateTime = cal.next(myLocalDateTime);
```

Thanks.

**Comment by jodastephen** [comment]
Firstly, it is important to note that not all holiday calendars refer to stock markets, thus it is likely that this would be separate data, probably keyed by MIC code.

Secondly, the rest of the Strata codebase does not have a need for market opening data, so it is unlikely we would add it until there is a need in the analytics.

**Comment by nimo23** [comment]
Okay, I understand. So feel free to close this issue or leave it open when there is a need for such analytics.
