### ISSUE TITLE
Having issues with IsdaCdsProductPricer.java

### ISSUE THREAD

**Issue by SundstromDS** [OpenGamma/Strata#1541]
Hello!

I'm trying to replicate and understand the results in your pdf of CDS valuation in: https://developers.opengamma.com/quantitative-research/Pricing-and-Risk-Management-of-Credit-Default-Swaps-OpenGamma.pdf. By using the "CORRECT" formula in your java implementation.

So first of i do not understand the present value formula in equation (48) in the referred document, where it says that one should subtract the integral for default, however in the java implementation it seems like the integral for default is added and not subtracted (line 552 in IsdaCdsProductPricer.java, 
pv += singlePeriodAccrualOnDefault(.)).  

Secondly for clean price, the accrued interest is obtained as zero (line 561 in IsdaCdsProductPricer.java, pv -= cds.accruedYearFraction(stepindate)). Where the step in date is 2011-06-13, so there should be accrued interest from the recent IMM date i.e. 2011-03-20?

Although i seem to get results in line with the tables in the referred pdf, i feel like i do not understand how it is mathematically correct.

Would greatly appreciate any help on this matter
// regards Dennis

**Comment by yukiiwashita** [comment]
On the first point, the definition of I^k includes the negative sign (see (45) and (46), compared with (18)). Thus (48) involves a typo. 
On the second point, `ResolvedCds#accruedYearFraction(LocalDate)` simply calculates the year fraction between the start date and the stepin date. So I am wondering whether the start date of your CDS is set to be 2011-03-20.
