### ISSUE TITLE
Trade CSV loader: add counterparty

### ISSUE THREAD

**Issue by marc-henrard** [OpenGamma/Strata#1582]
In TradeCsvLoader, add the loading of optional counterparty for the trades.
Two new optional columns should be allowed in the loader of all trades:
- Counterparty Scheme
- Counterparty
If present, the two should be combined into a StandardId and loaded into the 'counterparty' field of the TradeInfo associated to the trade.

**Comment by jodastephen** [comment]
Fixed by #1583
