### ISSUE TITLE
Monotone Cubic interpolator for zero rates

### ISSUE THREAD

**Issue by jodastephen** [OpenGamma/Strata#1657]
When converting a curve from discount factors to zero rates, it has proven necessary to have a new interpolator. Specifically, the discount factors use `LOG_NATURAL_SPLINE_MONOTONE_CUBIC` but there is no equivalent for zero rates.

**Comment by yukiiwashita** [comment]
The same is true for extrapolators. For example, we don't have the zero rate version of `QuadraticLeftCurveExtrapolator`.
