### ISSUE TITLE
Add Swaption in TradeCsvLoader

### ISSUE THREAD

**Issue by marc-henrard** [OpenGamma/Strata#1698]
Add swaptions to the types supported by the TradeCsvLoader.
The new fields should be
- Expiry Date
- Expiry Time
- Expiry Zone
- Long Short 
- Premium Currency 
- Premium Amount 
- Premium Date
- Settlement Type (for cash settlement add Settlement Date)

Example available in OG-Labs

**Comment by jodastephen** [comment]
Fixed in 7519c94d075fbefc888d190e03c14147bf6e9c09
