### ISSUE TITLE
IsdaCompliantCreditCurveCalibrator incorrectly selects sensitivities based on list index

### ISSUE THREAD

**Issue by jurna** [OpenGamma/Strata#1700]
When performing credit curve calibration, IsdaCompliantCreditCurveCalibrator selects curve sensitivities based on curve position in the list (get first)
https://github.com/OpenGamma/Strata/blob/master/modules/pricer/src/main/java/com/opengamma/strata/pricer/credit/IsdaCompliantCreditCurveCalibrator.java#L280
and 
https://github.com/OpenGamma/Strata/blob/master/modules/pricer/src/main/java/com/opengamma/strata/pricer/credit/IsdaCompliantCreditCurveCalibrator.java#L294

Returned sensitivities list is sorted based on marketDataName (which is curve name) and currency:
https://github.com/OpenGamma/Strata/blob/master/modules/market/src/main/java/com/opengamma/strata/market/param/CurrencyParameterSensitivity.java#L257

If we change curve name in such way, that order is different, we are receiving "Function returned array of incorrect length 20, expected 11" error, because sensitivities are taken from wrong curve.

To reproduce this case, you need to change FastCreditCurveCalibratorTest. You need to change the name of IsdaCreditCurveDefinition from "cc" to "zz":
https://github.com/OpenGamma/Strata/blob/master/modules/pricer/src/test/java/com/opengamma/strata/pricer/credit/FastCreditCurveCalibratorTest.java#L111

**Comment by yukiiwashita** [comment]
Thank you for reporting this issue. 
Because `CurrencyParameterSensitivities` in the functions involves sensitivities to the discount curve as well, the first element is not necessarily the credit curve sensitivities. 
The is fixed by #1703.

**Comment by yukiiwashita** [comment]
Closed by #1703.
