### ISSUE TITLE
Path definition issue 

### ISSUE THREAD

**Issue by mhafidi** [OpenGamma/Strata#1909]
in the class CalibrationPVPerformanceExample
instead of  : 
 /* Path to files */
  private static final String PATH_CONFIG = "src/main/resources/example-calibration/curves/";
  private static final String PATH_QUOTES = "src/main/resources/example-calibration/quote
use

 private static final String PATH_CONFIG = "examples"+File.separator+"src"+ File.separator+"main"+ File.separator+"resources"+ File.separator+
          "example-calibration"+ File.separator+"curves"+ File.separator;
  private static final String PATH_QUOTES = "examples"+File.separator+"src"+ File.separator+"main"+ File.separator+"resources"
          + File.separator+"example-calibration"+ File.separator+"quotes"+ File.separator;

by the way the same problem exists in other parts of the code --> this fix will make your code usable in different platforms

**Comment by jodastephen** [comment]
There is no need to do this. The paths work just fine on Windows (OpenGamma developers have a mixtiure of Windows and Mac and the CI is Linux, so this all gets tested.) If you can show a particular case that doesn't work, feel free to reopen.
