### ISSUE TITLE
"Mountain Day" August 11 missing for JPY

### ISSUE THREAD

**Issue by hyiger** [OpenGamma/Strata#1962]
Strata version 2.2.0

If Aug 11 falls on a weekend then it rolls forward to Monday. On Tuesday it rolls backward to Monday. Wed-Fri falls on that day

```
	@Test
	public void testHoliday() {
		HolidayCalendar jpyCalen = HolidayCalendarId.defaultByCurrency(Currency.JPY).resolve(REF_DATA);
		assertTrue(jpyCalen.isHoliday(LocalDate.of(2019, 8, 12)));
		assertTrue(jpyCalen.isHoliday(LocalDate.of(2020, 8, 10)));
	}
```

**Comment by jodastephen** [comment]
The test above passes in the latest version of Strata v2.3.2.

The current rule in Strata bumps Sunday and Tuesday to Monday. Can you confirm that Saturday is also bumped to Monday?

**Comment by jodastephen** [comment]
Looks like the actual rule in 2020 is [due to the olympics](https://www.loc.gov/law/foreign-news/article/japan-three-holidays-to-be-moved-to-ease-2020-olympic-ceremony-traffic/). Three holidays are being moved, but the normal rule for Mountain is only "bump Sunday to Monday".
