### ISSUE TITLE
Curve calibration: support for overriding the tenor associated with a node

### ISSUE THREAD

**Issue by jonathansenior** [OpenGamma/Strata#212]
By default the instrument implies the node date passed to the analytics during calibration (and the subsequent x value of that node on the calibrated curve), but it needs to be possible to override this regardless of the date implied by the instrument.

This is primarily to support node dates that align with ECB meeting dates. In this case, the node date would be defined as an index (after the current date) into a list of meeting dates.

We may also want to support overriding the node date to an alternative absolute or relative date as part of this.

**Comment by jodastephen** [comment]
The date can be overridden from code.
