### ISSUE TITLE
Add AMERIBOR overnight index in USD

### ISSUE THREAD

**Issue by marc-henrard** [OpenGamma/Strata#2258]
Add AMERIBOR to the list of overnight indices in USD
https://ameribor.net/ameribor-vs-other-benchmarks
Index used as underlying for some futures: https://markets.cboe.com/tradable_products/interest_rate/ameribor_futures
Swap market not developed at this stage

Details

Name | Currency | Active | Day Count | Fixing Calendar | Publication Offset Days | Effective Offset Days | Fixed Leg Day Count
USD-AMERIBOR | USD | TRUE | Act/360 | USNY | 0 | 0 | Act/360

**Comment by jodastephen** [comment]
Fixed by #2268
