### ISSUE TITLE
Possible Convention Issue

### ISSUE THREAD

**Issue by phil-zxx** [OpenGamma/Strata#2273]
Hi,

I hope it is ok to post this. I had been looking through the conventions provided by Strata, and found some to be inconsistent with what I see in Bloomberg. For example:

- In https://github.com/OpenGamma/Strata/blob/main/modules/product/src/main/java/com/opengamma/strata/product/swap/type/StandardFixedOvernightSwapConventions.java#L117-L118 I see `EUR_FIXED_1Y_ESTR_OIS = makeConvention(..., 2, 2)`, which means `paymentLag=2`. But the payment lag as per BBG is only 1 day:
![image](https://user-images.githubusercontent.com/32247590/103468966-ba1e3480-4d56-11eb-86e7-b59f003d1108.png)

- In https://github.com/OpenGamma/Strata/blob/main/modules/basics/src/main/resources/META-INF/com/opengamma/strata/config/base/IborIndexData.csv#L67 I see that both the fixed & float leg day-counters for `USD-LIBOR-3M` are marked as `Act/360`. However, in https://github.com/OpenGamma/Strata/blob/main/modules/product/src/main/java/com/opengamma/strata/product/swap/type/StandardFixedIborSwapConventions.java#L48-L52 it says that the fixed leg uses `30U/360`. But in BBG I see `30I/360` (is it the same as `30U/360`?):
![image](https://user-images.githubusercontent.com/32247590/103469178-5ea17600-4d59-11eb-91c2-03e131cd8a05.png)

- The entries `USD_FIXED_6M_LIBOR_3M`, `EUR_FIXED_1Y_EURIBOR_6M` and `CHF_FIXED_1Y_LIBOR_6M` in https://github.com/OpenGamma/Strata/blob/main/modules/product/src/main/java/com/opengamma/strata/product/swap/type/StandardFixedIborSwapConventions.java all use the exact same day-counter `30U/360`. But in BBG each of them has a different day-counter:
![image](https://user-images.githubusercontent.com/32247590/103477291-6858c700-4db5-11eb-9d33-2fdedf62061d.png)

Of course, BBG could be out of date, or I misunderstood Strata's setup, in which case I apologise.

---

Questions:
1. I hope you don't mind me asking this, but just to avoid any confusion: do files `StandardFixedOvernightSwapConventions.java` and `StandardFixedIborSwapConventions.java` merely contain sample conventions, or are they meant to be correspond to the "official" conventions (as seen in BBG)? And the same question for files `OvernightIndexData.csv` and `IborIndexData.csv`. Ultimately, I am wondering whether conventions are meant to be user-driven, or whether Strata aims to provide all conventions.
2. When defining e.g. `EUR_FIXED_1Y_ESTR_OIS = makeConvention(..., payLag, spotLag)`, there seems to be only one `payLag`, but what if the `payLeg` on the 2 legs is different? I only ask because BBG lists the attributes of each leg individually, and because the BBG Swap Manager SWPM lets you choose different offsets, different day counters, different holiday calendars, etc. for each leg individually. Is the same level of customisation possible with Strata?
3. When defining e.g. `IborRateSwapLegConvention.of(IborIndices.USD_LIBOR_3M)` where do the conventions of the index come from (such as `FixingDateOffset`, etc). Are they loaded from another file?

---

*Disclaimer: I am a Rates Quant, but I do not actually use Strata. I was merely looking at it, since it is open-source, and thought I'd raise the convention mismatches.*

**Comment by jodastephen** [comment]
Thanks for the input, we'll have to take a look.

On the questions, `StandardFixedOvernightSwapConventions` and `StandardFixedIborSwapConventions` should represent the best view on what market conventions are. Unfortunately, it isn't always easy to decide what is the most accurate convention so there are sometimes differences to BBG. Strata only provides enough conventions to get users started - if they want more they have to be added.

Strata has the ability for conventions to vary by leg. It may require a different set of method calls to achieve that, but it is possible. Most of the alterations supported by FpML are supported in Strata, including those your mention.

There are separate definitions for each index, eg in `IborIndexData.csv`

**Comment by phil-zxx** [comment]
Hi @jodastephen, thanks for answering my questions. This all makes sense.

Just checking if you had a chance to verify the possible convention mismatches on your side.

**Comment by marc-henrard** [comment]
Hi Phil,
Thanks for pointing those issues.
I will will start with the USD questions. For USD LIBOR swaps, there have been traditionally 2 conventions: SemiBond v LIBOR-3M (USD-FIXED-6M-LIBOR-3M in Strata) and Annual Money v LIBOR 3M (USD-FIXED-1Y-LIBOR-3M in Strata). In BBG, the latter would be USSAx. Both 30/360 and ACT/360 are correct in some sense. The last column in IborIndexData is used only if user want to create some automatic convention mechanism; it is not used for standard pricing.

**Comment by jodastephen** [comment]
Closing, as this seems to be answered
