### ISSUE TITLE
Act/Act ICMA Day-Counter

### ISSUE THREAD

**Issue by phil-zxx** [OpenGamma/Strata#2291]
Apologies for posting. Please do tell me if this is the wrong place.

I was looking at the implementation of `Act/Act ICMA` in [StandardDayCounts.java (lines 65-87)](https://github.com/OpenGamma/Strata/blob/main/modules/basics/src/main/java/com/opengamma/strata/basics/date/StandardDayCounts.java#L65-L87). For simplicity, lets assume `firstDate` and `secondDate` are neither the `StartDate` nor `EndDate` of the overall schedule, so that neither  `initPeriod` nor `finalPeriod` is called. Then I was wondering about two special cases:

1. `prevCouponDate = firstDate < secondDate < nextCouponDate`: We get
  ```java
actualDays = daysBetween(firstDate, secondDate);        // e.g. 300
periodDays = daysBetween(firstDate, nextCouponDate);    // e.g. 365
dcf = actualDays / (freq.eventsPerYear() * periodDays)  // e.g. 300/(1*365) = 0.822
```

2. `prevCouponDate < firstDate < secondDate = nextCouponDate`: We get
  ```java
actualDays = daysBetween(firstDate, secondDate);        // e.g. 300
periodDays = daysBetween(firstDate, nextCouponDate);    // e.g. 300
dcf = actualDays / (freq.eventsPerYear() * periodDays)  // e.g. 300/(1*300) = 1.00
```

So in case 2, the `dcf` is always `1.0`, no matter where `firstDate` is within the current period. Is this as intended? So I wonder if
- `periodDays = daysBetween(firstDate, nextCouponDate)`

should rather be
- `periodDays = daysBetween(prevCouponDate, nextCouponDate)` ?

Then the name `periodDays` would also be more fitting, as it would in fact correspond to the overall period. Please let me know if I misunderstood something.

**Comment by jodastephen** [comment]
These are the relevant docs:
https://www.isda.org/a/NIJEE/ICMA-Rule-Book-Rule-251-reproduced-by-permission-of-ICMA.pdf
https://www.isda.org/a/AIJEE/1998-ISDA-memo-%E2%80%9CEMU-and-Market-Conventions-Recent-Developments%E2%80%9D.pdf
The case you outline is not explicitly specified in the spec, but indirectly it would seem to agree with your analysis.

As it stands, there is no test for the use case as `firstDate` is supposed to be the period start date. But it looks like this can be addressed without breaking other use cases.
