### ISSUE TITLE
Date question

### ISSUE THREAD

**Issue by rfrerebe-stx** [OpenGamma/Strata#2487]
Hello,

I think that there is an issue here :
https://github.com/OpenGamma/Strata/blob/169e17c08fe1b415a7d5793eea5de5dc676ec1e0/modules/basics/src/main/java/com/opengamma/strata/basics/date/GlobalHolidayCalendars.java#L1301-L1307

Using `christmasBumpedSatSun` on year YYYY, if Christmas ( YYYY-12-25) is a Sunday then YYYY-12-27 (Tuesday) is added to holidays.
My understanding is that it should be YYYY-12-26 which should be added.

**Comment by jodastephen** [comment]
The method is used with `boxingDayBumpedSatSun`. The net result of the two methods correctly allocates the necessary dates, except in Montreal where there was a bug.
