### ISSUE TITLE
Test Smell: it is not a good practice to write the return statement in test cases

### ISSUE THREAD

**Issue by TestSmell** [OpenGamma/Strata#2499]
Hi!

I notice that you write a test case with a return statement.
<img width="206" alt="截屏2022-08-18 下午8 02 46" src="https://user-images.githubusercontent.com/110402847/185399325-f3e02373-d28d-4bbc-8ea3-9e266163ea04.png">

It is not a good idea to write the return statement in your test case.
So I would like to know if is it really a useful test case? 
Maybe I think you should remove the @Test annotation from this method ?

**Comment by davyboyhayes** [comment]
Given the comment on #2507, I suggest closing this as a duplicate (even though this is the first issue)?

**Comment by tyagi-data-wizard** [comment]
Hi, 

Created a PR for this issue.
[PR #2589](https://github.com/OpenGamma/Strata/pull/2589)

Please assign this issue to me and please let me know if any other changes are required.

**Comment by tyagi-data-wizard** [comment]
Hi @davyboyhayes ,

The  [PR](https://github.com/OpenGamma/Strata/pull/2589) has been merged, can you please assign the issue to me and close this issue.

Please do let me know in case anything else is needed to close the issue. (new to open source)

Thanks

**Comment by davyboyhayes** [comment]
I'm afraid I don't have access to assign anyone as I'm not an author on Strata
