### ISSUE TITLE
 AUSY contains Aug & Oct state-local holidays

### ISSUE THREAD

**Issue by simonmarshall** [OpenGamma/Strata#2503]
Hi all, the AUSY calendar includes Aug & Oct holidays, this year being Aug 1 & Oct 3 2022.

See here [Strata/GlobalHolidayCalendars.java at main · OpenGamma/Strata · GitHub](https://github.com/OpenGamma/Strata/blob/main/modules/basics/src/main/java/com/opengamma/strata/basics/date/GlobalHolidayCalendars.java#L956)

However, these are state-local holidays, and not exchange holidays, according to www.rba.gov.au/schedules-events/bank-holidays/
See www2.asx.com.au/markets/market-resources/trading-hours-calendar/cash-market-trading-hours/trading-calendar
and www.cboe.com.au/trading-information/market-holidays

These holidays should not be part of your AUSY holiday set, since they are not exchange holidays.

**Comment by jodastephen** [comment]
We primarily model settlement holidays for interest rate derivatives such as swaps. My understanding of the data is that the markets close for settlement on these dates. If you need a calendar for ASX, you would need a separate ID.
