### ISSUE TITLE
BigMoney does not behave like Money

### ISSUE THREAD

**Issue by andrey-nakin** [OpenGamma/Strata#2598]
It turns out that `BigMoney` works in a bit different way than `Money`.

An example:

```java
var bigMoney = BigMoney.of(Currency.USD, 123.456789);
System.out.println("BigMoney.value=" + bigMoney.getValue());
```

Output:

```
BigMoney.value=123.456789
```

Shoudn't it be `123.46` as when we use `Money`?

Here is a repository that demonstrates the issue: https://github.com/andrey-nakin/strata-issues/tree/BigMoney

**Comment by jodastephen** [comment]
As per the Javadoc:

    This class is similar to {@link Money}, but permits any number of decimal places.

In fact, the extended decimal places is the reason the class exists.
