### ISSUE TITLE
Scenarios: handling of market data with multiple aliases

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#260]
If the same curve is used for discounting and forward rates it will be stored in the market data map under two different market data IDs. This has potentially surprising consequences when scenarios are applied. 

For example, if a curve shift is specified using the curve name, both the discount and forward curves would be shifted. But if a shift is defined to apply to all discount curves, a shifted copy of the curve would be created for discounting but the forward curve would be unaffected.

This would also result in two curves stored in the market data map with the same name, one with and one without a shift applied. This is definiely wrong.

First we need to clarify what the expected behaviour is. Should a shift specified to apply to discount curves also affect a forward curve if the same curve is used for discounting and forward rates? Or should the act of shifting a curve create a new curve with a different name?

If the shift needs to affect both discount and forward curves the following changes will be needed:

* Add a level of indirection to the market data containers to allow multiple IDs to refer to a single underlying piece of market data
* Enhance the scenario framework so a perturbation applied to an item of market data can replace market data with a different ID that has already been built
* Add a market data function to store a curve in the market data using its name instead of discount+currency or forward+index
* Change the discount and forward curve market data functions to insert an alias into the market data instead of a curve

If discount and forward curves should be shifted independently, the only change required will be to create a new name for a curve when it is perturbed. This avoids having the same name in the market data referring to multiple different values.

**Comment by jodastephen** [comment]
This has been addressed.
