### ISSUE TITLE
Pricer measure: currency exposure

### ISSUE THREAD

**Issue by marc-opengamma** [OpenGamma/Strata#308]
For all pricers, create a new measure called "currencyExposure" and containing the first order equivalent to the currency risk of the instrument. The output is in the form of a MultiCurrencyAmount.

For simple instruments, the currency exposure will be the pv. But for instruments referring to a FxIndex or option on Forex, the computation will be more involved.

The FxIndex part will require implying the exposure from 'FxIndexSensitivity'.

**Comment by jodastephen** [comment]
Still need currencyExposure on FRA pricer

**Comment by jodastephen** [comment]
Done.
