### ISSUE TITLE
Consistent trade / flow direction

### ISSUE THREAD

**Issue by jonathansenior** [OpenGamma/Strata#381]
To introduce fields along the lines of:

trade.buySell = Buy
trade.fee.direction = BuyerPays
leg1.direction = SellerPays
leg2.direction = BuyerPays

or

trade.buySell=Buy
trade.fee.Payer=Buyer
leg1.Payer=Seller
leg2.Payer=Seller

**Comment by jodastephen** [comment]
No action was agreed for this issue.
