### ISSUE TITLE
Special case handling of double values in scenario market data

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#434]
Double values in scenario data are stored in a multimap with every other type of market data. It might be worth treating them as a special case at storing them in primitive arrays. That saves the overhead of boxing which can be significant for very large data sets.

There is a question about how the data should be returned to functions:

* Immutable `List<Double>` backed by the array - avoids changing the API exposed to functions
* `double[]` that is defensively copied - gives the data to functions in a compact form but lots of copying
* `double[]` that holds the underlying data - efficient but dangerous

**Comment by cjkent** [comment]
Suggested approach:

Create an `ImmutableDoubleArray` class wrapping a `double[]`. The input array can be defensively copied or used directly. The direct version should probably have "unsafe" in the name. The backing array is exposed, either defensively or directly via a method called "*unsafe".

So no copying will occur if the unsafe methods are used on construction and to access the backing array.

The market data lookup interface should have methods something like:

    ImmutableDoubleArray getDoubleValues(MarketDataKey<T> key); // defensive copy

    ImmutableDoubleArray getDoubleValuesUnsafe(MarketDataKey<T> key); // underlying array

**Comment by stuartarchibald** [comment]
Should the `Unsafe` call perhaps return a type which acknowledges that it is in fact mutable?

**Comment by cjkent** [comment]
We want people to treat it as if it were mutable. Mutating it is definitely an error. It's intended as an immutable array with an escape hatch where we'd like to guarantee immutability but can't because of the limitations of Java.

If we make it explicitly mutable then we should expect mutation and we should defensively copy the backing array. Which is exactly what we're trying to avoid.

What should it be called to communicate the fact that it's mutable if someone behaves badly but it is intended to be read-only?
