### ISSUE TITLE
CurveCurrencyParameterSensitivities equality depends on the ordering of its list of sensitivities

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#462]
It would seem intuitive that the ordering isn't important

**Comment by jodastephen** [comment]
The internal list is sorted and normalized, so list equality should work just fine. Not sure any change is needed here.

**Comment by cjkent** [comment]
The varags version of the `of` method doesn't sort or normalise the inputs, it calls the constructor directly with a copy of the input array.

That method should call the other `of` method, or the logic should be moved to the constructor.
