### ISSUE TITLE
Create "current cash" result for all instruments

### ISSUE THREAD

**Issue by marc-opengamma** [OpenGamma/Strata#472]
The "current cash" result register the amount of cash due on the valuation date. 
It is not a very important measure by itself, but an important part of a profit computation between two dates. To compute the profit, one compute the PV on two different date and the amount of cash which has been paid (or received) by the instruments (coupons, premium, etc). Without that measure, the profit computation for an instrument becomes almost meaningless.

**Comment by jodastephen** [comment]
Needed for FRA

**Comment by jodastephen** [comment]
Done.
