### ISSUE TITLE
Inflation bonds - pricer

### ISSUE THREAD

**Issue by ghost** [OpenGamma/Strata#549]
Inflation bonds: create pricer with at least the conventions for US (TIPS), France (OATi, OATie), and UK (Gilts)

Risk measures
- present value
- curve sensitivity (including inflation)
- current cash
- clean real price
- dirty real price
- accrued interest
- duration
- modified duration
- convexity

**Comment by jodastephen** [comment]
France still to do

**Comment by jodastephen** [comment]
`CapitalIndexedBond` added
