### ISSUE TITLE
Add type information to Measure

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#562]
It would be useful if `Measure` contained information about the type of value it produced.

This needs some thought, it might not be as simple as it seems on the surface because of scenarios. Some measures, for example PV, produce a single value for a single scenario (`double`) and multiple values for multiple scenarios (a subtype of `ScenarioResult<Double>`). However it's easy to imagine measures that produce the same type whether there is one scenario or many. For example the maximum or average PV across multiple scenarios is a `double` regardless of the number of scenarios.

Does this mean `Measure` requires 2 type parameters? Or that there needs to be 2 types of measure, one for individual values and one for values calculated across multiple scenarios?

**Comment by jonathansenior** [comment]
I think the effect that scenarios might have on the type probably belongs elsewhere, if anywhere. At the static Measure level I think what's important is to convey that a raw PV value is a `double`, while bucketed PV01 is another type, etc.

**Comment by cjkent** [comment]
One of the major reasons for having the type on the measure is knowing what type to expect when getting values from the results. This is OK for PV where the value for multiple scenarios is just multiple instance of the value for a single scenario. But it breaks down for multiple scenarios if a function does anything more complicated than simply populating a list with the value from each scenario.

I don't think it is sufficient to just have a single type parameter on `Measure` unless we introduce a different type of measure for values aggregated across multiple scenarios.

We might also have to look at `Results`. Currently the same object is used to return results from one scenario or many and it is up to the user to know whether they're getting a single or multiple values. For the type information on `Measure` to be useful we might need different `Results` types.

**Comment by cjkent** [comment]
This is potentially useful for controlling currency conversion. `FxConvertible` results will always be converted into a single currency amount at the moment and that might not always be what the users wants. If the measure specified the result had a type with multiple currencies the engine can skip the currency conversion.

**Comment by jodastephen** [comment]
After much thought, it was concluded that the impact on usability would be greater than the benefits. Some convenience methods to avoid casting were added instead.
