### ISSUE TITLE
Convert to CurrencyValuesArray during conversion to reporting currency

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#585]
`CurrencyValuesArray` is an efficient way of storing multiple currency values with the same currency. It is effectively a wrapper around a currency and a double array.

If a scalar pricer produces a `CurrencyAmount` or a `MultiCurrencyAmount` for each scenario they will be converted to a list of `CurrencyAmount` in the reporting currency. It would be possible to go one step further and convert them into a `CurrencyValuesArray` which is more memory efficient and potentially offers greater performance.

**Comment by jodastephen** [comment]
This issue is not really relevant anymore with the measures API structure.
