### ISSUE TITLE
More special cases in FunctionUtils.toScenarioResult

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#587]
If the results are all `CurrencyAmount` instances they can be packed into a `CurrencyValuesArray` and if they are `MultipleCurrencyAmount` instances they can be packed into the `MultipleCurrencyValuesArray` (see #586).

**Comment by cjkent** [comment]
This needs thinking about. If `CurrencyAmount` instances are packed into a `CurrencyValuesArray` by `FunctionUtils.toScenarioResult` the return type of the function is `ScenarioResult<CurrencyAmount>`. 

This means the currency amounts will be unpacked into a double array, but when the results are consumed every value will have to be packed into another `CurrencyAmount`. The effect is that the results will be more compact but require more processing.

It might be better to convert functions to use a collector that explicitly creates a `CurrencyValuesArray`. This would allow consumers of the results to get the values without needing to wrap them in a `CurrencyAmount` and without needing to cast the `ScenarioResult`.

**Comment by cjkent** [comment]
If we make this change it also needs to be done in `ScenarioResult.of`.

**Comment by cjkent** [comment]
Since the changes to `CalculationFunction` the objections to this change don't seem to be relevant. The results are returned from functions in a `Map<Measure, Result<?>>` so the type information about the return value has already been discarded.

When we add typed measures #562 the user will see the actual concrete type of `CurrencyValuesArray` or `MultiCurrencyValuesArray` when extracting the value from the results using the `Measure`.

**Comment by jodastephen** [comment]
Other changes mean that this issue is not really relevant anymore.
