### ISSUE TITLE
Ensure all values collected by FunctionUtils.toScenarioResult are of the same type

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#602]
This seems like a reasonable restriction; why would the same calculation produce a different type in a different scenario when the only thing different is the market data? It would also make the implementation of #587 simpler and more efficient.

**Comment by jonathansenior** [comment]
Agree - calculations should produce a consistent type for any valid inputs, and we should enforce this assumption. If a different type is needed for some reason then this would be a different measure.

**Comment by jodastephen** [comment]
This method is rarely used now.
