### ISSUE TITLE
New exception type thrown when looking up data with an unknown identifier

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#603]
Something like `DataNotFoundException`. Currently we throw `IllegalArgumentException` which means it's impossible to distinguish between looking up data using an unknown ID and passing in genuinely invalid data.

This came up in a conversation about mapping exception types to HTTP errors in a REST framework. It is pretty natural to map `IllegalArgumentException` to 400 (bad request) and `DataNotFoundException` to 404 (not found).

**Comment by jodastephen** [comment]
Fixed by https://github.com/OpenGamma/Strata/commit/b241971b973c3805ad04147dd5c8765c3e9c703b
