### ISSUE TITLE
Reporting the same value in multiple currencies

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#609]
This is a feature we've talked about and started to implement but never finished or even fully designed.

The `CurrencyAwareCalculation*Function` interfaces were designed to be able to handle this but have never been wired up to the engine. They are capable of returning values in multiple currencies but it's not clear how that can happen because `ReportingRules` only returns a single reporting currency at the moment.

The engine performs currency conversion into the reporting currency for the regular calculation functions, and it seems reasonable that the engine should be able to convert one value into multiple currencies if the user requests it.

The things we need to think about are:
- Do we actually need this functionality?
- How can a user request multiple currencies? Should `ReportingRules` return a `Set<Currency>`?
- Does this create an extra column in the results? So the results have more columns than the user requested? Or does the user request identical columns with different reporting currencies and the engine merges them for calculations and unmerges them to create the results?
- How should we return the results from functions? A specialised `Result` variant? Using maps everywhere might be heavy when most of the time they will have one currency and therefore one element.

**Comment by jonathansenior** [comment]
I think we keep it simple: any column the user wants to see in the output has to be requested as a column in the input, and this includes the single reporting currency for that column. If they want the same measure in multiple currencies then each would be a separate column with different `ReportingRules`.

We can optimise the engine to calculate the measure once and do the currency conversion multiple times later.

**Comment by jodastephen** [comment]
When the calculation code was refactored to have multiple measures per function execution, this issue was fixed. Calling a calculation with two columns calculating PV, but with different reporting currencies, only invokes the underlying calculation once.
