### ISSUE TITLE
Fine grained control over currency conversion

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#615]
A mechanism is needed to easily enable or disable currency conversion. At the moment it is done automatically but there are cases where this loses information which the user requires, for example when returning `CurveCurrencyParameterSensitivities`.

There is an existing mechanism which disables conversion by wrapping the individual result values in a `ScenarioResult` that doesn't implement `FxConvertible`. This isn't exposed on any functions in a way that is user configurable, and it will never work for functions which return convertible `ScenarioResult` implementations directly, for example `CurrencyValuesArray`.

In some cases the type of the value is changed by currency conversion, for example `MultiCurrencyValuesArray` is converted to `CurrencyValuesArray`. Currency conversion is not optional in these cases as changing the return type when the configuration changes will break the consuming code.

An obvious mechanism would be to use function arguments in pricing rules to enable or disable currency conversion. The problem with this approach is that there is no way to target arguments at individual functions, so currency conversion would be enabled or disabled for the whole group of functions. We decided that function arguments applied to the whole group for simplicity. This might be a reason to reconsider that design unless someone thinks of another way to achieve it.

**Comment by cjkent** [comment]
One option would be to skip currency conversion if all of the following are true:

1. The function returns `empty` from `defaultReportingCurrency`
2. The reporting rules return `empty` from `reportingCurrency`
3. The the type of the result is compatible with the expected return type

This wouldn't require any changes to the configuration mechanism to make it work. However the only way to verify 3 is to implement #562 and attach type information to the measure.

**Comment by cjkent** [comment]
Another option would be to keep the existing mechanism and add a method to `FxConvertible` returning a boolean which signals whether currency conversion should be skipped.

**Comment by cjkent** [comment]
This should be fixed when #740 is addressed.

**Comment by jodastephen** [comment]
Use `ReportingCurrency.NONE`.
