### ISSUE TITLE
Consider MarketDataBox.ofSingleValue and ofScenarioValues

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#655]
The original idea was that a market data box with a single value would be completely distinct from a market data box with multiple values. A single value box could be used with any number of scenarios and a multiple value box could only be used with a fixed number of scenarios matching the number of values in the box.

At some point a scenario box with a single value became equivalent to a single value box. Which makes me wonder whether there's any point having a different type and different factory methods for single and multiple value boxes. We could have a single factory method `MarketDataBox.of` and different behaviour if the box contains one value or multiple values.

The obvious problem is that the fundamental difference between a box with one value and a box with multiple values isn't so obvious without the separate factory methods. If we think that's important maybe we should reverse the decision to make a scenario box with one value behave like a single value box.

**Comment by jodastephen** [comment]
I find the definition that a scenario box with a single value is the same as a singe value box slightly odd. I'd welcome attempts to see if that can be sorted,
