### ISSUE TITLE
Rename CurrencyValuesArray and MultiCurrencyValuesArray

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#716]
They are a bit of a mouthful, `CurrencyArray` and `MultiCurrencyArray` are shorter and no less descriptive.

**Comment by jodastephen** [comment]
I'd consider `CurrencyArray` to be an array of currencies. Given the choices, I think the current name is the best we can do.

**Comment by cjkent** [comment]
Fair enough
