### ISSUE TITLE
List generation inefficiency

### ISSUE THREAD

**Issue by fmovlex** [OpenGamma/Strata#783]
I've noticed this issue in `PeriodicSchedule.java` - it probably exists in other spots as well.
Take for example `PeriodicSchedule#generateBackwards` (line 493 or 499 on my version) - and consider a non standard internal swap (e.g. float-float, pay 1m, over 50y, pay/rec legs -> ~1200 payment periods).

Using an `ArrayList` copies a giant amount of increasingly-sized arrays - and in a portfolio with hundreds of these swaps (or during HVaR) things get messy.
Using an `ArrayDeque` here and optimizing inserts for head/tail will really help here - for example, instead of adding `end` and `start` (which forces you to insert at position 1), use a `Deque` and head-insert everything, then head-insert `start` last.

I'm not really familiar with anything except swaps so I hesitate to change things myself, but a review of similar list-generating methods (and especially backward-generating) across the library would likely boost performance.
Thanks guys

**Comment by jonathansenior** [comment]
Thanks for raising this. Looking at the code, I can see the inefficiency you describe due to the repeated insertion at position 1. Using an `ArrayDeque` and inserting only at the head would work nicely - thanks for the suggestion.

I couldn't find any other instances of similar logic, but this issue will affect all products with initial stubs. Out of interest, did you find this by profiling?

**Comment by fmovlex** [comment]
We had a similar performance hit in my firm's swap pricer - it just caught my eye while looking through the `leg#expand` process.

There's a whole bunch of performance "gotchas" we've gathered from pricing swaps and especially calculating VaR which I'll happily share whenever I can - but since my view is limited to interest rates at the moment, it'll take some learning.

**Comment by jodastephen** [comment]
My testing didn't find a major slowdown as a result of the insertion at index 1 pattern. I've raised a R to address it, using a private `List` implementation that acts like `ArrayDeque`.
