### ISSUE TITLE
Port interpolators to Strata

### ISSUE THREAD

**Issue by jodastephen** [OpenGamma/Strata#805]
The remaining implementations of `Interpolator1D` need to be ported to implement `CurveInterpolator`. Three have been ported so far (Linear, LogLinear and DoubleQuadratic). The following are still to be done:

- Natural Cubic Spline
- PCHIP
- PiecewisePolynomial subclasses
- ProductPiecewise
- SquareLinear
- Step
- StepUpper
- TimeSquare
- Transformed

I'd suggest doing `SquareLinearInterpolator1D` first

**Comment by jodastephen** [comment]
Constants in `CurveInterpolators` give an indicator of the subset considered most important.

**Comment by jonathansenior** [comment]
We may not need all of these to be ported. Interpolators definitely required:

* LOG_NATURAL_CUBIC_MONOTONE
* LOG_NATURAL_CUBIC_DISCOUNT_FACTOR

**Comment by davidcervi** [comment]
All interpolators defined in CurveInterpolators have now been successfully ported.

**Comment by jodastephen** [comment]
Any additional interpolators can be added as needed.
