### ISSUE TITLE
Revisit function configuration and pricing rules

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#807]
The way in which functions are configured was designed when each function calculated a single measure and the function instances didn't know about the measures. That has since changed; functions calculate multiple measures and are aware of the measures they calculate.

It is likely the config can be simplified by using this extra information available on the function. Even if the current mechanism needs to be retained for maximum flexibility, we should be able to build simple configuration much more easily for the common case.

**Comment by jodastephen** [comment]
This no longer applies with the redesign of strata-calc.
