### ISSUE TITLE
General purpose Indexed type to replace ScenarioMarketDataValue and ScenarioResult

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#815]
`ScenarioMarketDataValue` was created to hold market data for multiple scenarios. `ScenarioResult` was created to hold calculated values for multiple scenarios. They are fundamentally very similar; they are simple containers for multiple values with a type parameter for the elements, a size and an accessor to look up a value by index.

It has become apparent that some values implementing these interfaces are generally useful, for example `CurrencyValuesArray` and `MultiCurrencyValuesArray`. It would be good if these types could be decoupled from the market data and calculation APIs. Also, there are some types which could be both market data and calculated values.

It should be possible to replace `ScenarioMarketDataValue` and `ScenarioResult` with a single type, possibly called `Indexed`.

`ScenarioResult` has special handling in the calculation code to unwrap result values when calculating values for a single scenario. In order to preserve this we would need a new container similar to the existing `Result` type but specifically for scenarios. We could probably reuse the name `ScenarioResult` for this.

**Comment by cjkent** [comment]
I started work on a prototype of this and it's a much bigger change than I first thought.

`CalculationFunction.calculate` returns a map of measure to `Result`. As part of this change, `Result` would become an interface with implementations `ScenarioResult` and `SingleResult`

Most market data functions are structured as a map of measure to method reference, where the method calculates the measure. The value returned from the method is the raw value, not a `Result`.

The calculation function invokes the methods for all of the measures, wrapping each value in a `Result` and populating the map of results.

If this change were implemented, the measure methods would have to return a `Result` indicating whether the calculated value is a scenario value or a single value. This is quite an intrusive change which would touch every calculation function and would also put `Result` on a lot more APIs which might not be desirable.

**Comment by jodastephen** [comment]
Step one could be to merge the two interfaces (`ScenarioArray`?), with implementations folding as appropriate.

**Comment by cjkent** [comment]
That would definitely be a step forward and much less intrusive.

**Comment by jodastephen** [comment]
`ScenarioArray` added. And that is as far as we should go.
