### ISSUE TITLE
All CombinedInterpolatorExtrapolator instances are considered equal!

### ISSUE THREAD

**Issue by traggatt** [OpenGamma/Strata#834]
CombinedInterpolatorExtrapolator does not override hashCode or equals so inherits the basic implementation from Interpolator1D which just compares classes.

CombinedInterpolatorExtrapolator is typically used to combine extrapolation and interpolation functionality for old platform interpolators. It therefore renders any of the equals/hashcode implementations for the other interpolators useless.

There are roughly 21 subclasses of Interpolator2D, so it would be worth checking that none of these also have this bug as long as they are in use in Strata.

**Comment by jodastephen** [comment]
This class no longer exists.
