### ISSUE TITLE
Expose ReferenceData to the scenario framework

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#839]
The scenario framework needs security metadata to operate. This is now stored in `ReferenceData`. This needs to be passed to `MarketDataFilter.matches` and `ScenarioPerturbation.applyTo`.

**Comment by jodastephen** [comment]
Looking at this, it seems that it complicates the API for an occasional use case. One option would be for the `ScenarioPerturbation` implementation to hold a `ReferenceData` if it needs it.

**Comment by cjkent** [comment]
I'm not sure about that. Ideally the definition of a scenario should be completely reusable as it's just a set of rules for matching and manipulating market data. Baking the reference data into the perturbation instances means they would have to be recreated every time they are used.
