### ISSUE TITLE
Analytics sensitivities-type risk computations report sensitivity to 100% shift on underlying

### ISSUE THREAD

**Issue by traggatt** [OpenGamma/Strata#846]
Commonly a user would expect to see sensitivity to a 1BP shift rather than a 100% shift. The existing API  inconveniences them by forcing a divide by 10,000 whenever handling results. (Or, if they are not aware of the convention, substantially alarming them first!)

The current design assumes sensitivity to a 100% shift to avoid any ambiguity between inter-analytics calls. e.g. If function A depends on a sensitivity result from function B, it can always rely on the unit of the return value.

Potential solutions include:

- change global standard to report 1BP sensitivity
- define (and clearly document!) different quote conventions per product type - in certain places use 1BP, 100% in others
- introduce a new object which explicitly specifies the result unit for all analytics calls, thus avoiding any ambiguity

**Comment by jodastephen** [comment]
The new measures-level API provides this functionality.
