### ISSUE TITLE
Add high-level swaption pricing API

### ISSUE THREAD

**Issue by traggatt** [OpenGamma/Strata#847]
There only needs to be two - one for the SwaptionTrade and another for the SwaptionProduct (i.e. with and without premium, respectively).

The current set of pricers is the cartesian product of:

- 2 settlement types: cash/physical
- 3 model types: black, SABR and normal, plus another general supertype pricer for shared measure implementations

Plus:

- 1 hull/white pricer which only works for `SwaptionProduct`
- another 7 which only work for `SwaptionTrade`

For most of these elements, it should be possible to infer the model, and settlement type from the input arguments. The model is defined by the type of `Volatilities` object passed and the settlement type by the `SwaptionProduct`.

There does not appear to be any reason why the public API can't expose a single set of functions as most pricing functions have the same argument and result types per product/trade. 

In the case where additional functions exist for a specific model type, these could still exist on the same pricing API but take a narrower set of arguments. e.g:

Function callable for any model and settlement type:
````
  public CurrencyAmount presentValue(
      SwaptionProduct swaption,
      RatesProvider ratesProvider,
      SwaptionVolatilities swaptionVolatilities)
````

Function callable only for SABR (since it only takes `SabrSwaptionVolatilities` as opposed to more general `SwaptionVolatilities`):
````
  public PointSensitivityBuilder presentValueSensitivity(
      SwaptionProduct swaption,
      RatesProvider ratesProvider,
      SabrSwaptionVolatilities swaptionVolatilities) {
````

**Comment by jonathansenior** [comment]
Very valid point. I think there's simply a missing high-level API here. A lot of effort has already gone in to normalising the swaption pricing in Strata so that ultimately a single pricer is driven by different input data types (rather than having entirely separate pricers, as in OG-Platform). It makes sense that we should be able to benefit from this with a single swaption pricing API.

**Comment by jodastephen** [comment]
Done.
