### ISSUE TITLE
Consider adding convenience methods for sensitivity calculations to pricers.

### ISSUE THREAD

**Issue by traggatt** [OpenGamma/Strata#849]
Currently trade/product pricers typically only support calculating point sensitivities on the trade. However the most common use case will usually be to calculate sensitivities to relevant objects in the market data environment passed.

For swaps, getting market rate sensitivities is currently done over three calls to three different APIs:

````
PointSensitivities tradeSensitivities = SWAP_PRODUCT_PRICER.presentValueSensitivity(swapProduct, provider).build();
CurveCurrencyParameterSensitivities parameterSensitivities = provider.curveParameterSensitivity(tradeSensitivities);
CurveCurrencyParameterSensitivities result = MarketQuoteSensitivityCalculator.DEFAULT.sensitivity(parameterSensitivities, provider);
````

It would be convenient to have a single method call on the pricer for this.

**Comment by traggatt** [comment]
A method such as `presentValueSensitivityMarketRates()` could be added for this.

**Comment by jodastephen** [comment]
As designed, strata-pricer is a low level API. The high level API and mapping to measures occurs in strata-function. This is but one of many examples of the difference between the APIs.

**Comment by traggatt** [comment]
How is this different from the convenience methods on [DiscountingSwapTradePricer](https://github.com/OpenGamma/Strata/blob/master/modules/pricer/src/main/java/com/opengamma/strata/pricer/swap/DiscountingSwapTradePricer.java) for PV'ing a swap trade?

**Comment by jodastephen** [comment]
Measures API added to handle this.
