### ISSUE TITLE
Add query methods to FxRateProvider

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#876]
Most market data containers have a mechanism for querying whether data is available. In some cases this is implemented with a `get` method throwing an exception and a `find` method returning `Optional`. We also have some types with `contains` methods to avoid the overhead of creating an `Optional`.

`FxRateProvider` is different. It only has the `fxRate` methods returning `double` and throwing an exception if no rate is available. This means it is impossible to efficiently implement an `FxRateProvider` which decorates another rate provider and automatically creates cross rates when necessary.

**Comment by jodastephen** [comment]
It seems that we have other solutions to cross-rates.
