### ISSUE TITLE
Consider naming of FxSingle class and pricers

### ISSUE THREAD

**Issue by traggatt** [OpenGamma/Strata#888]
The [`FxSingle`](https://github.com/OpenGamma/Strata/blob/master/modules/product/src/main/java/com/opengamma/strata/product/fx/FxSingle.java) class is used to model either an FX Forward or FX Spot trade. However this is non-standard nomenclature and so non-intuitive for the first-time user. 

Indeed, the only classes which show up when searching types for `FxForward` are:

![screen shot 2016-04-01 at 17 07 45](https://cloud.githubusercontent.com/assets/4661772/14212755/4cdf9668-f82c-11e5-81c5-6ac29cba202e.png)

It suggests some aspect of FX Forward pricing is supported, but it is not immediately obvious where this is.

Consider potential solutions:

* Rename class to `FxForward` and document that it may also be used to model FX Spot transactions.
* Make abstract and add `FxForward` and `FxSpot` as subclasses.
* etc

Pricers also follow the same naming convention. e.g. [`DiscountingFxSingleProductPricer`] (https://github.com/OpenGamma/Strata/blob/master/modules/pricer/src/main/java/com/opengamma/strata/pricer/fx/DiscountingFxSingleProductPricer.java). In the same vein, it would probably be desirable to rename/refactor these also.

**Comment by traggatt** [comment]
Another minor point - [`of()`](https://github.com/OpenGamma/Strata/blob/master/modules/product/src/main/java/com/opengamma/strata/product/fx/FxSingle.java#L108) methods use naming `currencyAmount1` and `currencyAmount2`. It would be better to be consistent with the internal naming of the fields - `baseCurrencyAmount` and `counterCurrencyAmount`.

**Comment by jodastephen** [comment]
The name used by FpML is `FxSingleLeg`.

Separate classes do not work, as there is no way to validate that the date really is the spot date. Ultimately, the classes are identical in meaning and pricing, with just the implied meaning of the date changing. (Plus, each separate type requires a lot of related classes)

**Comment by traggatt** [comment]
This makes sense. Analytics around the `FxSingle` are identical whether the trade is a spot or forward so, when the trade is resolved, they should ultimately price using the same object.

In terms of modelling the unresolved trade, perhaps the `FxSpot` contract could be defined in relative terms instead of absolute. For example, it could just contain a single field: `daysToSpot`, indicating the days remaining between now and the spot date. When resolved against a specific valuation date/calendar, this would then be crystallised into an absolute date. This would also leave the door open to adding spot conventions down the line which resolve into `FxSpot` trades.

**Comment by jodastephen** [comment]
I'd expect spot convention to hold a `DaysAdjustment` representing the days between trade date and spot date. The actual `FxSingle` class cannot contain elements relative to now, as they represent an actual trade.

**Comment by jodastephen** [comment]
Closing, with agreemnet that conventions will be named FxSpot and FxForward.
