### ISSUE TITLE
Check holiday calendar for USD-FED-FUND index

### ISSUE THREAD

**Issue by cjkent** [OpenGamma/Strata#892]
The holiday calendar for this index is NYFD. Some of the datasets I'm working with only include the USNY for New York which causes pricing to fail.

Is this holiday calendar ID correct? Is it effectively an alias for USNY?

**Comment by jacbop** [comment]
ISDA distinguishes between New York Fed (NYFD) and  NYSE.

2006 ISDA Definitions Section 1.9 and 1.10

FpML distinguishes between New York Fed (NYFD),  NYSE and USNY.

I don't see USNY referenced in the 2006 ISDA Definitions.

**Comment by cjkent** [comment]
I've looked into it further and I think the holiday data is incomplete. In the old platform (which is where the data came from) the USNY calendar was used for the USD-FED-FUND index so it wouldn't have been necessary to include the NYFD data.
