### ISSUE TITLE
StubConvention.of(StubConvention.SHORT_INITIAL.name()) throws an IllegalArgumentException

### ISSUE THREAD

**Issue by mobrahim** [OpenGamma/Strata#904]
```java
StubConvention.of(StubConvention.SHORT_INITIAL.name()) 
```
will throw: 

```java
java.lang.IllegalArgumentException: No enum constant
com.opengamma.strata.basics.schedule.StubConvention.S_H_O_R_T__I_N_I_T_I_A_L
```
This will work :
```java
StubConvention.of(StubConvention.SHORT_INITIAL.toString()) 
```

The fact that .name() is available in the API and returns a formatted string that is different from what is expected from the ENUM (I suppose because of the implicit use of Joda convert) is confusing in this case

**Comment by jodastephen** [comment]
Just to note that 

    StubConvention.of(StubConvention.SHORT_INITIAL.toString()) 

will work.

We could alter the enums to handle either input format however.

**Comment by jodastephen** [comment]
Examined this, but it is impractical to parse more formats.
