### ISSUE TITLE
Convention - node: Fed Fund Swap

### ISSUE THREAD

**Issue by ghost** [OpenGamma/Strata#906]
Add a new convention/template/node type to support Fed Fund swaps: ON arithmetic average v Ibor.

**Comment by marc-opengamma** [comment]
Add a new type of convention, template and curve node. The underlying swap is a basis swap Overnight v Ibor.
The most used version is in USD, called Fed Fund swaps. The overnight leg is quarterly Arithmetic Average of overnight versus Libor 3M. Note the 'arithmetic average', which is different from the standard OIS which trade with composition.
Some overnight v Libor are also traded in GBP.

**Comment by jodastephen** [comment]
Added  `OvernightIborSwapConventions`
